

DROP TABLE BOARDTEST;

CREATE TABLE BOARDTEST (

BOARDKEY NUMBER PRIMARY KEY,
TITLE VARCHAR2(100) NOT NULL,
CONTENT VARCHAR2(1000) NOT NULL,
AUTHOR VARCHAR2(100) NOT NULL,
WRITEDATE DATE DEFAULT SYSDATE,
FILENAME VARCHAR2(300),
FILENAMEORIGIN VARCHAR2(300),
READCOUNT NUMBER

);



CREATE TABLE DELETEFILE(
FILENAME VARCHAR2(300) NOT NULL);